### ISSUE TITLE
Mod operator

### ISSUE THREAD

**Issue by MiccDev** [gibbsly/gm#11]
Could you add a function that takes in two macros x and y and it returns the remainder of x divided by y.

**Comment by gibbsly** [comment]
I have been contemplating a way to do it and I have yet to come up with anything, although I will try to come up with something

**Comment by GlitchlessCode** [comment]
I will also take a look into this, if I get the time

**Comment by gibbsly** [comment]
added with https://github.com/gibbsly/gm/pull/13
